services:

  #  Base de données PostgreSQL
  postgres:
    image: postgres:15-alpine
    container_name: sinistrapro-db
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - sinistrapro-network

  # Backend Spring Boot
  backend:
    build:
      context: ./SinistraPro/demo
      dockerfile: Dockerfile
    container_name: sinistrapro-backend
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/${POSTGRES_DB}
      SPRING_DATASOURCE_USERNAME: ${POSTGRES_USER}
      SPRING_DATASOURCE_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "8100:8100"
    depends_on:
      - postgres
    networks:
      - sinistrapro-network

  #  Frontend React
  frontend:
    build:
      context: ./sinistrapro-front
      dockerfile: Dockerfile
    container_name: sinistrapro-frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
    networks:
      - sinistrapro-network

volumes:
  postgres_data:

networks:
  sinistrapro-network:
    driver: bridge

















